set(VCPKG_TARGET_ARCHITECTURE x64)
set(VCPKG_CRT_LINKAGE dynamic)
set(VCPKG_LIBRARY_LINKAGE dynamic)
set(VCPKG_BUILD_TYPE release)

# Windows 7+ API surface (matches MinGW triplet)
set(VCPKG_C_FLAGS   "-D_WIN32_WINNT=0x0601")
set(VCPKG_CXX_FLAGS "-D_WIN32_WINNT=0x0601")
